apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-emqx-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
